version: '3'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: base_image:latest

  langserver:
    build:
      context: .
      dockerfile: chesster/langserve/Dockerfile.langserve
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY
      - LANGSERVE_SECRET

  app:
    build:
      context: .
      dockerfile: chesster/app/Dockerfile.app
    ports:
      - "8000:8000"
    environment:
      - LANGSERVE_SECRET
